#!/bin/bash

#DEFINE COMMMAND

DEFINE_PROJECT() {
	projectid_cust=$(openstack role assignment list --user $emailcust --user-domain neo.id | awk '{print $7}' | head -4 | tail -1)
}


#MAIN PROCESS

clear

echo "==============================
C E  I N V O K E R  T O O L S
==============================
Select Region :
1. JKT2
2. WJV2
3. BTN
"

read -p "Enter Your Choice : " number

case "$number" in

1)  region="JKT2"
    ;;
2)  region="WJV2"
    ;;
3)  region="BTN"
    ;;
*) clear
	echo
        echo "HEY!!! BISA BACA NGGAK????"
        echo
	exit 0;;
esac

source ./functions/mainmenu.sh

